// MT-15: the published storefront `(site)` route group is decoupled from the
// editor's root layout. These assertions lock in two guarantees:
//   1. The storefront supplies its OWN, neutral metadata (NOT the editor's
//      "Create Next App" scaffolding) via `(site)/layout.tsx`.
//   2. A storefront miss renders the `(site)` 404 (clean, no editor chrome),
//      not the editor-root not-found.

import { describe, it, expect, afterEach } from 'vitest';
import React from 'react';
import { render, screen, cleanup } from '@testing-library/react';

import { generateMetadata } from '../layout';
import SiteNotFound from '../not-found';

// The exact editor scaffolding that used to leak from the root layout into the
// storefront `<head>`. The storefront must never emit these.
const EDITOR_TITLE = 'Create Next App';
const EDITOR_DESCRIPTION = 'Generated by create next app';

afterEach(() => cleanup());

describe('(site) layout metadata', () => {
  it('returns storefront metadata, not the editor "Create Next App" defaults', async () => {
    const metadata = await generateMetadata();

    expect(metadata.title).not.toBe(EDITOR_TITLE);
    expect(metadata.description).not.toBe(EDITOR_DESCRIPTION);
    // It defines its own neutral storefront defaults rather than inheriting the
    // editor's.
    expect(metadata.title).toBeDefined();
    expect(JSON.stringify(metadata)).not.toContain(EDITOR_TITLE);
    expect(JSON.stringify(metadata)).not.toContain(EDITOR_DESCRIPTION);
  });
});

describe('(site) not-found', () => {
  it('renders the storefront 404 with no editor chrome', () => {
    render(<SiteNotFound />);

    expect(screen.getByTestId('storefront-404')).toBeTruthy();
    expect(screen.getByRole('heading', { name: /page not found/i })).toBeTruthy();
    // No editor scaffolding text bleeds into the storefront 404.
    expect(screen.queryByText(EDITOR_TITLE)).toBeNull();
  });
});
