import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// NOTE (MT-15): the data-table-react CMS-grid stylesheets + cms-grid-theme.css
// used to be imported HERE, in the root layout, which ships them to EVERY route
// — including the published storefront under `(site)`, which has no data-table.
// In the App Router only the root layout owns `<html>`/`<body>`, so it wraps the
// storefront too; the root layout is therefore kept NEUTRAL. The grid CSS now
// lives on the editor surfaces (`src/app/page.tsx` for `/` and
// `src/app/projects/layout.tsx` for `/projects/*`), so it only loads on editor
// routes, never the published storefront.

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Neutral root metadata (MT-15): the old "Create Next App" / "Generated by
// create next app" defaults were editor scaffolding that leaked into the
// storefront `<head>`. The storefront supplies its own metadata via
// `src/app/(site)/layout.tsx` + per-page `generateMetadata`; editor surfaces
// can set their own titles. Keep this empty so nothing editor-specific ships to
// published sites.
export const metadata: Metadata = {};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
