import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// Notion-style CMS grid (data-table-react). Classes/vars are `dt-*`-namespaced,
// so importing these globally does not bleed into the editor chrome.
import "@marlinjai/data-table-react/dist/styles/variables.css";
import "@marlinjai/data-table-react/dist/styles/base.css";
// Re-light the data-table after its stylesheets: pin its --dt-* tokens to the
// light theme + the Studio iris accent. The engine auto-switches to a dark glass
// theme under `@media (prefers-color-scheme: dark) :root:not(.light)`, so the
// `.light` class on <html> below + these overrides keep the CMS grid clean and
// on-brand regardless of the OS theme.
import "./cms-grid-theme.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
