// scripts/commerce-codegen.ts
//
// CM-05 — regenerate the typed `CommerceDB` interface (src/server/commerce/
// db-types.ts) from the LIVE per-tenant DDL, so the type contract can never
// silently drift from the CM-04 migration set.
//
// HOW IT WORKS. kysely-codegen introspects a real Postgres schema, so this
// script stands up a throwaway one:
//   1. boot a disposable `postgres:16-alpine` via testcontainers (TRUST auth, so
//      no password literals — mirrors provision.itest.ts / backstop.itest.ts);
//   2. create the low-privilege `commerce_app` role (the per-migration REVOKEs
//      are guarded on its existence), then `migratePublic` + `provisionTenant`
//      with COMMERCE_TENANT_MIGRATIONS to materialise one real `tg_<id>` schema;
//   3. run the `kysely-codegen` CLI against it with `--default-schema tg_<id>`,
//      so the 19 commerce tables get BARE keys and `public.tenant_groups` keeps
//      its `public.` prefix — i.e. the public-prefix discipline shape directly;
//   4. post-process (header + the trigger-column reconciliation kysely-codegen
//      cannot infer) and write src/server/commerce/db-types.ts.
//
// RUN IT:  pnpm db:codegen-commerce   (requires Docker; never runs at build time)
//
// IMPORTANT — the COMMITTED db-types.ts is the CONTRACT; this script only
// REFRESHES it when the DDL changes. kysely-codegen cannot see that
// `product_variant.option_signature` is trigger-maintained (it would emit a
// plain insertable `string | null`), so the post-process wraps it in
// `Generated<>` and the operator should eyeball the diff before committing.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';

import postgres from 'postgres';
import { GenericContainer, Wait, type StartedTestContainer } from 'testcontainers';
import {
  assertTenantGroupId,
  migratePublic,
  provisionTenant,
  tenantSchema,
} from '@marlinjai/tenant-db';

import { COMMERCE_TENANT_MIGRATIONS } from '../src/server/commerce/migrations/tenant/index';

const DB_NAME = 'framer_clone_codegen';
const APP_ROLE = 'commerce_app';
// A fixed throwaway tenant-group id: the derived schema name is deterministic so
// the `--default-schema` flag and the post-process are reproducible run-to-run.
const TG = assertTenantGroupId('018f9c10-0000-7000-8000-0000000000c5');
const SCHEMA = tenantSchema(TG);

const OUT_FILE = fileURLToPath(
  new URL('../src/server/commerce/db-types.ts', import.meta.url),
);

/**
 * Apply the reconciliations kysely-codegen cannot infer from introspection:
 *  - `product_variant.option_signature` is maintained EXCLUSIVELY by triggers
 *    (003_catalog), so it must be `Generated<...>` (never inserted/updated), but
 *    introspection sees only a nullable TEXT column.
 * Returns the reconciled source. (The committed file carries a richer header +
 * per-table comments; an operator reconciles those by hand from this output.)
 */
function reconcile(raw: string): string {
  let out = raw;

  // option_signature: wrap the introspected nullable TEXT in Generated<>.
  out = out.replace(
    /option_signature:\s*string\s*\|\s*null;/,
    'option_signature: Generated<string | null>;',
  );

  const header =
    '// GENERATED by scripts/commerce-codegen.ts (pnpm db:codegen-commerce).\n' +
    '// The committed db-types.ts is the hand-reconciled CONTRACT — review the\n' +
    '// diff (esp. the Generated<> trigger columns) before committing.\n\n';
  return header + out;
}

async function main(): Promise<void> {
  let container: StartedTestContainer | undefined;
  let owner: postgres.Sql | undefined;
  try {
    container = await new GenericContainer('postgres:16-alpine')
      .withEnvironment({
        POSTGRES_USER: 'postgres',
        POSTGRES_PASSWORD: 'postgres',
        POSTGRES_DB: DB_NAME,
        // trust auth: roles log in by username alone, no password literals.
        POSTGRES_HOST_AUTH_METHOD: 'trust',
      })
      .withExposedPorts(5432)
      .withWaitStrategy(
        Wait.forLogMessage(/database system is ready to accept connections/, 2),
      )
      .start();

    const host = container.getHost();
    const port = container.getMappedPort(5432);
    const ownerUrl = `postgresql://postgres@${host}:${port}/${DB_NAME}`;
    owner = postgres(ownerUrl, { max: 1, prepare: false });

    // The app role must exist before migrating (REVOKEs are guarded on it).
    await owner.unsafe(`CREATE ROLE ${APP_ROLE} LOGIN`);

    await migratePublic(owner);
    await provisionTenant(owner, {
      tenantGroupId: TG,
      slug: 'cm05-codegen',
      appRole: APP_ROLE,
      tenantMigrations: COMMERCE_TENANT_MIGRATIONS,
    });

    const rawOut = join(mkdtempSync(join(tmpdir(), 'commerce-codegen-')), 'raw.ts');

    // Run the kysely-codegen CLI. `--default-schema <tg>` yields BARE keys for
    // the commerce tables and a `public.`-prefixed key for tenant_groups (the
    // discipline shape). `--exclude-pattern` drops the runner's bookkeeping
    // tables; `--no-domains` keeps output to tables only.
    execFileSync(
      'pnpm',
      [
        'exec',
        'kysely-codegen',
        '--url',
        ownerUrl,
        '--dialect',
        'postgres',
        '--default-schema',
        SCHEMA,
        '--exclude-pattern',
        '*.__*',
        '--exclude-pattern',
        'public.tenant_migration_progress',
        '--out-file',
        rawOut,
      ],
      { stdio: 'inherit' },
    );

    const reconciled = reconcile(readFileSync(rawOut, 'utf8'));
    writeFileSync(OUT_FILE, reconciled, 'utf8');
    console.log(`Wrote ${OUT_FILE}. Review the diff before committing.`);
  } finally {
    await owner?.end();
    await container?.stop();
  }
}

main().catch((err) => {
  console.error('db:codegen-commerce failed:', err);
  process.exitCode = 1;
});
